### ISSUE TITLE
the newer v2 embedding, causing a conflict with the plugin's older code.

### ISSUE THREAD

**Issue by romangazi121** [jgithaiga/flutter_sms_inbox#24]
[!] Consult the error logs above to identify any broken plugins, specifically those containing  │
│ "error: cannot find symbol..."                                                                  │
│ This issue is likely caused by v1 embedding removal and the plugin's continued usage of removed │
│ references to the v1 embedding.

**Comment by alastairR** [comment]
+1

Is there any chance you could upgrade this package for the new Android plugins API?
https://docs.flutter.dev/release/breaking-changes/plugin-api-migration

**Comment by Sahad2701** [comment]
Hi @romangazi121 👋,

This issue has been resolved in [this commit](https://github.com/jgithaiga/flutter_sms_inbox/commit/48e6468bd8e78512949f7c47d142459cb0eeb534), which migrates the plugin to use Pigeon and the latest Flutter v2 embedding.

You can use this version in your pubspec.yaml like so:

```
flutter_sms_inbox:
  git:
    url: https://github.com/jgithaiga/flutter_sms_inbox.git
    ref: 48e6468bd8e78512949f7c47d142459cb0eeb534
```

✅ This version works with the latest Flutter versions and resolves the cannot find symbol errors related to the deprecated v1 embedding.
